# -*- mode: ruby -*-
# vi: set ft=ruby :

# Instead of typing '--provider=lxc' all the time
ENV['VAGRANT_DEFAULT_PROVIDER'] = "lxc"

Vagrant.configure(2) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "fgrehm/trusty64-lxc"

  config.vm.provider "lxc" do |lxc|
  #  # Sets the name of the container
  #  lxc.container_name = 'mysql'
  #
  #  # Sets the backing store
  #  lxc.backingstore = "lvm"
  #
  #  # Sets cgroups parameters
  #  lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
  #
  #  lxc provider documentation can be found at https://github.com/fgrehm/vagrant-lxc
  end
end